### ISSUE TITLE
[Bug] BetterFormattingRedux in forums

### ISSUE THREAD

**Issue by speedlorenzo12** [zerebos/BetterDiscordAddons#673]
**Which plugin/theme is this about?**
BetterFormattingRedux v2.3.14

**Describe the Bug**
when you enter a forum channel when you are creating a post the icon to open the bfr section is positioned below the text

**To Reproduce**
enter a forum and create a post and put the mouse so that it is on the text

**Expected Behavior**
put it in a spot but it doesn't fit under the text (the only problem is that there is little space in the forum creation area)

**Screenshots**
![Screenshot (26 2)](https://user-images.githubusercontent.com/111771663/197364716-41f995b5-911c-4608-a8d5-419f3158868a.png)
![Screenshot (25 1)](https://user-images.githubusercontent.com/111771663/197364744-ed0b0155-056a-48ae-8095-a4399bec8e17.png)

**Discord Version**
Stable

**Comment by rauenzi** [comment]
Is this still an issue? it does not appear in that location for me

![image](https://github.com/rauenzi/BetterDiscordAddons/assets/6865942/ce989fec-2a79-46dd-a42f-7b6d2cf3ec9f)

**Comment by speedlorenzo12** [comment]
Prove in forum or bio
