### ISSUE TITLE
[Feature] BetterRoleColors per server or per color overrides for legibility

### ISSUE THREAD

**Issue by FearNaBoinne** [zerebos/BetterDiscordAddons#723]
**Which plugin/theme is this about?**
BetterRoleColors

**Is your feature request related to a problem? Please describe.**
Some servers have role colors that are so close to the background color of the Discord window, the text is illegible.
To be able to read it, I have to select the text. As a result it would be better to simply disable the plugin for THOSE servers

**Describe the feature you'd like**
An option to either add servers on which BRC should NOT be active, or a way to override specific colors with different ones (ie 0x313338 > 0xb8b8b8, 0x391752 > 0x6e2c9e)

**Comment by 2J4YZ** [comment]
I second this. An option to specify a role color (such as black) and have it recolor to another would be great as well.

**Comment by zerebos** [comment]
You can technically already do per-color overrides with CSS and I am unlikely to add this at this point.
