### ISSUE TITLE
[Feature] I wanna see the user name on Permission Viewer, not the user id.

### ISSUE THREAD

**Issue by UnknownUserFromJapan** [zerebos/BetterDiscordAddons#724]
**Which plugin/theme is this about?**
Permission Viewer.

**Is your feature request related to a problem? Please describe.**
If the users who have the permission are shown with their user ids, that will make people hard to find the user quickly. 

**Describe the feature you'd like**
I wanna see the display name (ex: ABCDE#1234) of the users who has the permission that I can see on the Permission Viewer.

As the picture shows, users are displayed with their user id.
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/122227344/050e0737-407b-4955-9e4d-635b99d2f94a)

**Comment by rauenzi** [comment]
The latter is using an unsupported plugin and not associated with anything of mine.

**Comment by UnknownUserFromJapan** [comment]
> The latter is using an unsupported plugin and not associated with anything of mine.

Ah i’m really sorry with that. 
I’ve just deleted the picture.

**Comment by zerebos** [comment]
This was implemented along the way
