### ISSUE TITLE
Better Role Colors Does not show the color of the typing user anymore

### ISSUE THREAD

**Issue by Zaphodjoe** [zerebos/BetterDiscordAddons#727]
**Which plugin/theme is this about?**

BetterRoleColorsv0.10.1by Zerebos

**Describe the Bug**

It used to show the role color of the person typing's role now everyone's typing is just white

**To Reproduce**

**Expected Behavior**

**Screenshots**

**Discord Version**

Stable

**Additional Context**

**Comment by legonerd605** [comment]
it's because the user has a display name, display names are handled different than usernames

**Comment by zerebos** [comment]
Sorry but BetterRoleColors has been discontinued. I recommend using [MoreRoleColors](https://betterdiscord.app/plugin/MoreRoleColors).
