### ISSUE TITLE
[Feature] adding a colored role dot or a role symbol infront of user name in voice chat

### ISSUE THREAD

**Issue by jpfl** [zerebos/BetterDiscordAddons#730]
**Which plugin/theme is this about?**

BetterRoleColors

**Is your feature request related to a problem? Please describe.**

no problem.

**Describe the feature you'd like**

adding a colored role dot or a role symbol infront of user name in voice chat.
currently it can only color usernames of voice chat participants in a specific color.

the plugin betterRoleDot can add colored dots but only to the chat user list on the right but does not add anything to the voice chat user list on the left.

I would like to be able to identify a role by a unique symbol per role or an identical symbol but with role specific colors of voice chat participants.

**Additional context**

**Comment by jpfl** [comment]
what also would be na great feature is to be able to not just color the Bot Tag's background but also give the "Live" Tag of streaming users in voice chat with a color specific color.

**Comment by zerebos** [comment]
Sorry but BetterRoleColors has been discontinued. I recommend using [MoreRoleColors](https://betterdiscord.app/plugin/MoreRoleColors). I will CC the creator @daddyboard about your feature request!
