### ISSUE TITLE
[Feature] [BetterRoleColors] Add support for advanced markdown like headers

### ISSUE THREAD

**Issue by Fungustober** [zerebos/BetterDiscordAddons#738]
**Which plugin/theme is this about?**

BetterRoleColors

**Describe the Bug**

BetterRoleColors doesn't apply role colors to Header text in messages made using Discord's recent Markdown functionality.

**To Reproduce**

Type a #, a space, and then any text into Discord's message bar and send it.

**Expected Behavior**

I expected the Header text to also have color like the rest of the text in a message.

**Screenshots**

<img width="507" alt="Screenshot 2023-10-31 223359" src="https://github.com/rauenzi/BetterDiscordAddons/assets/58476370/c6488f8b-950a-4e9f-ac73-918d95e90ca3">
<img width="499" alt="Screenshot 2023-10-31 223410" src="https://github.com/rauenzi/BetterDiscordAddons/assets/58476370/63f5a9d4-8d2e-4b97-8f94-58889564b216">

**Discord Version**

Stable

**Additional Context**

From investigating this, it seems that discord wraps the header markdown text in two spans, and then a h1, h2, or h3 element. I managed to select them in my own project by using `div[class*="messageContent"] h1 span span` but admittedly that was a quick and dirty solution after Discord's update wrecked everything.

**Comment by zerebos** [comment]
Sorry but BetterRoleColors has been discontinued. I recommend using [MoreRoleColors](https://betterdiscord.app/plugin/MoreRoleColors). I will CC the creator @daddyboard about your feature request!
