### ISSUE TITLE
[Bug] is the BlurNSFW plugin gonna get any updates ?

### ISSUE THREAD

**Issue by Imu-D-sama** [zerebos/BetterDiscordAddons#740]
**Which plugin/theme is this about?**
BlurNSFW

**Describe the Bug**
it just doesn't blur anymore

**To Reproduce**
its always there

**Expected Behavior**
to blur the NSFW

**Screenshots**
I'm not giving a screenshot of an NSFW as I got flashbanged in the face

**Discord Version**
Stable

**Additional Context**
just please fix it

**Comment by RenegadeScooter** [comment]
Same here, I can't scroll past all the art without it :(

**Comment by vEonz121** [comment]
the current version of BlurNSFW does not work on latest version of discord and BetterDiscord.

**Comment by RenegadeScooter** [comment]
@rauenzi
You there?

**Comment by RenegadeScooter** [comment]
There have been no updates to the plugin for **over a year** now.

**Comment by Mantas-2155X** [comment]
I ended up remaking BlurNSFW into [BlurMedia](https://github.com/Mantas-2155X/BlurMedia) which is more appropriate for my needs, it is functional but has feature changes

**Comment by zerebos** [comment]
This plugin has been fixed
