### ISSUE TITLE
[Other] The Upsidedown feature in BetterFormattingRedux makes some characters look awkward.

### ISSUE THREAD

**Issue by gs-jeong** [zerebos/BetterDiscordAddons#745]
**Which plugin/theme is this about?**
BetterFormattingRedux

**Problem**
When applying the existing Upsidedown format, there is an issue where some characters appear awkward. Therefore, although not addressing all characters, I have made changes to some of them to appear more natural. Could you please review the pull request?

before change
uppercase 
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/73513927/0c826edb-7b9e-4b5b-a867-9d90befcf393)
lowercase
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/73513927/0fac46f6-c789-447a-af1f-113526805129)
number
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/73513927/061b8b81-3d05-4d1f-ac83-8d0af7c7768d)

after change
uppercase
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/73513927/ca35ddd5-6046-41da-8760-e29b5be13233)
lowercase
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/73513927/efa88157-4c7d-4d4e-8e31-27fc3d1d589d)
number
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/73513927/af3e5817-15bd-45c6-bc7e-2f1f9dd0365f)

**Comment by zerebos** [comment]
Fixed in the merged PR
