### ISSUE TITLE
[Bug] [BlurNSFW] Not working at all

### ISSUE THREAD

**Issue by thickmelon** [zerebos/BetterDiscordAddons#751]
**Which plugin/theme is this about?**

- BlurNSFW

**Describe the Bug**

- Blurring media won't work at all.

**To Reproduce**

It's been months so there's not much of a step but:

1. Update Discord with the new API that broke the Cyberpunk 2077 theme (the API that made the portraits not work anymore)
2. BlurNSFW stops working

**Expected Behavior**

- Blurring starts working again

**Screenshots**

**Discord Version**

- Canary, PTB

**Additional Context**

**Comment by BigBoss320** [comment]
As of today, still not working. There is a BlurMedia that exists but blurs everything. I am trying to modify it but i have no skill with this...

**Comment by QuentinMcCarthy** [comment]
Can confirm, it's no longer working. It was working in channels prior to today for me, but it's stopped working entirely now.

**Comment by zerebos** [comment]
Just pushed out a new version that should work! Update will be live on the site soon!
