### ISSUE TITLE
[Bug] RoleMembers does not show a list anymore when hovering above the button in the context menu

### ISSUE THREAD

**Issue by jack652** [zerebos/BetterDiscordAddons#753]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
RoleMembers does not show a list anymore when hovering above the button in the context menu

**To Reproduce**
1. right click a discord server
2. hover above the RoleMembers button in the context menu

**Expected Behavior**
the roles list is shown

**Screenshots**
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/48365199/dbcf72fa-f08b-4222-8b26-c06794363d56)

**Discord Version**
Discord stable **274388** (865dbf6) Host 1.0.9035 x86 (44780) Windows 11 64-bit (10.0.22631)
BetterDiscord stable **1.10.0**

**Comment by MLangeEU** [comment]
The same bug is also with the PermissionViewer.
