### ISSUE TITLE
[Bug] PermissionViewer | Roles are not displayed

### ISSUE THREAD

**Issue by MLangeEU** [zerebos/BetterDiscordAddons#754]
**Which plugin/theme is this about?**

Plugin: PermissionViewer

**Describe the Bug**

Nothing works at all in the overview for the servers (first screenshot). The same applies when I press the permission button for a user (second screenshot). If I click on the permission button for a channel, a window appears where no roles are visible (third screenshot).

**To Reproduce**

Right click on Server -> Permission 
Right Click on User -> Permission
Right Click on Channel -> Permission

**Expected Behavior**

I expected the list of roles and the associated permissions to be displayed as usual.

**Screenshots**

_all screenshots are in german, the blue marked buttons are the permission buttons_
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/99598583/299b4ea0-ff1c-459d-b42c-573c1008de3a)
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/99598583/989bde83-4388-4a51-b515-4c272bda2d8e)
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/99598583/602d9ab0-ae5e-487d-8c26-201275d86994)

**Discord Version**

```md
## Discord Info
stable 274388 (865dbf6) Host 1.0.9035 x86 (44780) Windows 11 64-bit (10.0.22631)

## BetterDiscord
stable 1.10.0

## Plugins (4 Enabled):
- PermissionsViewer (Enabled)
- RoleMembers (Enabled)
- ShowHiddenChannels (Enabled)
- ZeresPluginLibrary (Enabled)

## Themes (0 Enabled):
```

**Additional Context**

**Comment by Madagarian** [comment]
Additional info: The black bar visible in the last screenshot *is* the permission field, but the name is not displaying. On a channel with several role overrides, there will be several closely grouped black bars that can be individually clicked on and interacted with, as expected. It seems the name is just no longer displaying.

**Comment by Pharaoh2k** [comment]
Excellent bug report. An annoying issue indeed, which cripples this amazing plugin. Hopefully will get fixed very soon...

**Comment by zerebos** [comment]
Please try the latest version
