### ISSUE TITLE
[Bug] PermissionsViewer don't show role name 

### ISSUE THREAD

**Issue by GSonicZ** [zerebos/BetterDiscordAddons#757]
**Which plugin/theme is this about?**
PermissionsViewer

**Describe the Bug**
PermissionsViewer menu don't show role name

**To Reproduce**
Open permission menu

**Expected Behavior**
Show role name

**Screenshots**
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/56105213/3528f61c-a8f0-4a11-b3cf-769a90cd22d7)

**Discord Version**
Stable 277953 (2ff410b)

**Additional Context**
-

**Comment by ehl0el** [comment]
Same issue here :(

**Comment by kokofixcomputers** [comment]
Same

**Comment by kokofixcomputers** [comment]
<img width="539" alt="Screenshot 2024-03-27 at 11 49 14 AM" src="https://github.com/rauenzi/BetterDiscordAddons/assets/113046561/2dcdd50f-e46e-4410-bed1-f825263652b4">

**Comment by zerebos** [comment]
Please try the latest version
