### ISSUE TITLE
[Bug] Context Menu not working / users roles permissions list don't show

### ISSUE THREAD

**Issue by Ichinistes14** [zerebos/BetterDiscordAddons#758]
**Which plugin/theme is this about?**
PermissionsViewer Plugin

**Describe the Bug**
When I click on the Permission button on servers, the context menu don't show up.
For users, we don't see there permission under the roles.
And for channels/categorys, it show up the context menu but no role are visible (Screenshots °2).

**To Reproduce**
Show click on Permissions button or try to view users permissions under their profile.

**Expected Behavior**
Expected to view permissions for everything, like it worked before Discord make update.

**Screenshots**
Error in console :
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/141771041/c22adfa4-57c7-4a33-bda4-955751769fa9)
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/141771041/00ba3162-6e40-47c3-a144-1dbcf589a7fc)
What Context Menu show :
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/141771041/673ca271-b12e-411d-83a8-a38a1351e1fe)

**Discord Version**
Stable Version

**Comment by 1dontkillme** [comment]
same
