### ISSUE TITLE
RoleMembers plugin not working [Bug] 

### ISSUE THREAD

**Issue by LexMari** [zerebos/BetterDiscordAddons#761]
**Which plugin/theme is this about?**
RoleMembers plugin

**Describe the Bug**
When loading the plugin into BD (I also have the Zerebos plugin library) The member from mention does not load, and nor does the context menu.

**To Reproduce**
Just install the plugin, and try to view the context menu

**Expected Behavior**
Should be able to see the roles/members

**Screenshots**
![bugreport](https://github.com/rauenzi/BetterDiscordAddons/assets/56957932/fb35161e-70e9-4cb7-9684-a72fc96dc6c8)
Not sure why it appears twice, probably because I tried replacing the file

**Discord Version**
Stable

**Comment by LexMari** [comment]
I did some slight look back and I found the fixed version here: https://github.com/ShaneMcC/rauenzi-BetterDiscordAddons/blob/ShaneMcC-RoleMembers/Plugins/RoleMembers/RoleMembers.plugin.js

**Comment by KaKi87** [comment]
Thanks for the info, the same person [fixed PermissionsViewer](https://github.com/ShaneMcC/rauenzi-BetterDiscordAddons/blob/ShaneMcC-PermissionsViewer/Plugins/PermissionsViewer/PermissionsViewer.plugin.js) as well !
