### ISSUE TITLE
[Bug] BetterRoleColors no longer works.

### ISSUE THREAD

**Issue by Runkel79** [zerebos/BetterDiscordAddons#762]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
BetterRoleColors no longer colors user names (the only thing that's working at the moment is coloring chat messages and the audit log)

**To Reproduce**
Install the plugin

**Expected Behavior**
Coloring user names (Voice, Pop out and so on)

**Discord Version**
```md
## Discord Info
stable 285182 (3f80edd) Host 1.0.9041 x86 (46355) Windows 11 64-bit (10.0.22621)

## BetterDiscord
stable 1.10.1

### Plugins (9 Enabled):
- BDFDB (Enabled)
- BetterChatNames (Enabled)
- BetterRoleColors (Enabled)
- CallTimeCounter (Enabled)
- Double Click To Edit (Enabled)
- HideDisabledEmojis (Enabled)
- PluginRepo (Enabled)
- ThemeRepo (Enabled)
- ZeresPluginLibrary (Enabled)

### Themes (0 Enabled):
- ClearVision
- RadialStatus
```

**Additional Context**
Even with all other Themes/Plugins disabled it doesn't work, so it's unlikely a conflict with another plugin.

**Comment by Amb33r** [comment]
Hello 

Same with me , I'll ask you to fix it if you find a moment

**Comment by DaddyBoard** [comment]
@rauenzi are you still maintaining this project?

**Comment by Ciruzzo73** [comment]
Any news ? Same problem here...

**Comment by Amb33r** [comment]
https://github.com/rauenzi/BetterDiscordAddons/issues/762#issuecomment-2068165573
