### ISSUE TITLE
[Bug] BetterRoleColors doesn`t work 21.04

### ISSUE THREAD

**Issue by iidddkkk** [zerebos/BetterDiscordAddons#763]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
at some point, the colors of the roles in the nicknames stopped being displayed, apparently after some kind of discord update

**To Reproduce**
install the plugin

**Expected Behavior**
Coloring user names (Voice, Pop out and so on)

**Discord Version**
```
 Discord Info
stable 286349 (4b5188e) Host 1.0.9042 x86 (46669) Windows 10 64-bit (10.0.19045)

## BetterDiscord
stable 1.10.1

### Plugins (1 Enabled):
- BDFDB
- BetterFriendList
- BetterRoleColors (Enabled)
- CallTimeCounter
- ChannelTabs
- FriendsSince
- GameActivityToggle
- ImageUtilities
- PluginRepo
- ReadAllNotificationsButton
- Timezones
- Translator
- ZeresPluginLibrary

### Themes (0 Enabled):
- midnight
```

**Additional Context**
it doesn't work even if you reinstall everything and turn off all other plugins

**Comment by helladamnleet** [comment]
Doesn't do anything for me either. I wasted half an hour thinking maybe I'm just dumb, but no, "Better Discord" is just garbage.

**Comment by Riddim-GLiTCH** [comment]
> Doesn't do anything for me either. I wasted half an hour thinking maybe I'm just dumb, but no, "Better Discord" is just garbage.

its just one plugin bruh. Anyway, you could have just upvoted the issue.

**Comment by helladamnleet** [comment]
> > Doesn't do anything for me either. I wasted half an hour thinking maybe I'm just dumb, but no, "Better Discord" is just garbage.
> 
> its just one plugin bruh. Anyway, you could have just upvoted the issue.

Actually it was every plugin I tried because like many Bethesda games almost every good plugin requires a single dependency plugin that never gets updated
