### ISSUE TITLE
[Bug] PermissionViewer not working

### ISSUE THREAD

**Issue by emircmd** [zerebos/BetterDiscordAddons#764]
yes.

**Comment by w4tchdoge** [comment]
I'm also experiencing issues with PermissionsViewer, here are some errors from the console as none have been provided by OP.
<img width="404" alt="image" src="https://github.com/rauenzi/BetterDiscordAddons/assets/28806101/a95b6f3a-8cc2-4acc-8f75-f8d6c3f0f045">

**Comment by allahin** [comment]
because I also can't access the developer console  😐

**Comment by Pharaoh2k** [comment]
Dunno why the pull request with the fix hasn't been merged yet, but here's the file with the fix:
https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/25498956b3dcd484eeb93506a9c39c7d3b68570c/Plugins/PermissionsViewer/PermissionsViewer.plugin.js

**Comment by PervyJoker** [comment]
> Dunno why the pull request with the fix hasn't been merged yet, but here's the file with the fix: https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/25498956b3dcd484eeb93506a9c39c7d3b68570c/Plugins/PermissionsViewer/PermissionsViewer.plugin.js

that code in that link worked fine for me ! just had to edit the plugin in discord and remove the original code in there and then paste the code from that link you had there with the code and save it and now everything works fine ! :D It promped me to update the app right after i saved it but its just a matter of not updating it and you should be fine :) lets hope the dev can update the app with that code or something so everything will be fine again ! :D

**Comment by dary1337** [comment]
> Dunno why the pull request with the fix hasn't been merged yet, but here's the file with the fix: https://raw.githubusercontent.com/rauenzi/BetterDiscordAddons/25498956b3dcd484eeb93506a9c39c7d3b68570c/Plugins/PermissionsViewer/PermissionsViewer.plugin.js

thx its works
