### ISSUE TITLE
[Bug]  Fix BetterRoleColors

### ISSUE THREAD

**Issue by itzroger22** [zerebos/BetterDiscordAddons#766]
FIX BETTER ROLE COLORS PLZ 😭😭😭😭😭

**Comment by BialySztorm** [comment]
i think the thing which causing the crushing is only typing indicator, i'm still testing if the issue occuring with dissabled the typing option, but at least, not crushing for now

**Comment by lextatic** [comment]
> i think the thing which causing the crashing is only typing indicator, i'm still testing if the issue occuring with dissabled the typing option, but at least, not crashing for now

I tested you PR and it didn't seem to fix the colors for the Voice chat users. But I also hadn't had any crashes with this plugin previously either. It's simply not working anymore.

**Comment by BialySztorm** [comment]
> > i think the thing which causing the crashing is only typing indicator, i'm still testing if the issue occuring with dissabled the typing option, but at least, not crashing for now
> 
> I tested you PR and it didn't seem to fix the colors for the Voice chat users. But I also hadn't had any crashes with this plugin previously either. It's simply not working anymore.

Yeah, as I write in description I only figured out account description fix and pop ups username only, but the voice I not done yet.

**Comment by vicimpa** [comment]
Guys) Check it
```js
            patchVoiceUsers() {
                const { React } = BdApi;
                Patcher.after(VoiceUser.prototype, "renderName", (thisObject, _, returnValue) => {
                    if (!this.settings.modules.voice) return;
                    if (!returnValue || !returnValue.props) return;
                    const member = this.getMember(thisObject?.props?.user?.id);
                    if (!member || !member.colorString) return;

                    return React.createElement(
                        'div',
                        {
                            style: {
                                display: 'contents',
                                ['--channels-default']: member.colorString,
                                ...(this.settings.global.saturation ? {
                                    ["data-accessibility"]: "desaturate"
                                } : {}),

                            }
                        },
                        returnValue
                    );
                });
            }
            ```

**Comment by vicimpa** [comment]
![telegram-cloud-photo-size-2-5249400456596284034-x](https://github.com/user-attachments/assets/5b642a7e-8d20-4eb5-8d3b-0f881d174a75)
[BetterRoleColors.plugin.js.zip](https://github.com/user-attachments/files/16321703/BetterRoleColors.plugin.js.zip)

**Comment by vicimpa** [comment]
I fix it)

**Comment by lextatic** [comment]
> I fix it)

You are a god! Thanks!

**Comment by vicimpa** [comment]
Yo) I small refactor and fix color with hover and active micro
[BetterRoleColors.plugin.js.zip](https://github.com/user-attachments/files/16323208/BetterRoleColors.plugin.js.zip)
Developers, please check. I can make pull request.

**Comment by wilecoyote** [comment]
@vicimpa your file is working but memberlist headers are not colored.

**Comment by vicimpa** [comment]
> @vicimpaВаш файл работает, но заголовки списка участников не окрашены.

What do you mean?

**Comment by wilecoyote** [comment]
It should be the same color as the bot's name
![image](https://github.com/user-attachments/assets/e882559d-1d60-41f2-91c0-2a1eef875ef9)
because of this plugin setting
![image](https://github.com/user-attachments/assets/7d3e9265-dfdc-4ad6-b150-10499da2d5af)

**Comment by alexbofa** [comment]
> Yo) I small refactor and fix color with hover and active micro [BetterRoleColors.plugin.js.zip](https://github.com/user-attachments/files/16323208/BetterRoleColors.plugin.js.zip) Developers, please check. I can make pull request.

Thanks, that's work!

Please update https://github.com/zerebos/BetterDiscordAddons/blob/master/Plugins/BetterRoleColors/BetterRoleColors.plugin.js
@zerebos
