### ISSUE TITLE
[Feature] BetterRoleColors in message box

### ISSUE THREAD

**Issue by TimoNotThy** [zerebos/BetterDiscordAddons#769]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the feature you'd like**
When typing a message the regular color (or the theme color) for pings is shown. Only after the message is send does the color of the ping adhere to the plugin. The point is to have the [BetterRoleColors](https://github.com/rauenzi/BetterDiscordAddons/tree/master/Plugins/BetterRoleColors) everywhere right?
**Additional context**

While my role color is red my ping color in the message input box is pink (which is configured by my theme)
![image](https://github.com/rauenzi/BetterDiscordAddons/assets/67267822/b00ab0a4-5bf3-49ea-9cca-ebe7dc606b7d)
For those wondering: My discord is in IRC mode, that's why it looks like this.

**Comment by zerebos** [comment]
Sorry but BetterRoleColors has been discontinued. I recommend using [MoreRoleColors](https://betterdiscord.app/plugin/MoreRoleColors) this feature was actually added to that plugin!
