### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by REDCATED8491** [zerebos/BetterDiscordAddons#770]
**Which plugin/theme is this about?**: Permission Viewer

**Describe the Bug**: Roles when checking permissions of a channel not showing.

**To Reproduce**: Just right click and click Permissions.

**Expected Behavior**: To show the roles.

**Screenshots**: How do I take screenshots with the UI immediately disappearing when clicking something else lol.

**Discord Version**: Stable

**Additional Context**: N/A

**Comment by Hugo16bm** [comment]
Still bugged :/
