### ISSUE TITLE
[Bug] Role members bug

### ISSUE THREAD

**Issue by yarross** [zerebos/BetterDiscordAddons#771]
![Screenshot_64](https://github.com/rauenzi/BetterDiscordAddons/assets/73038106/d68ba184-bc3b-404f-8e36-d864e26a22c8)

**Comment by AndreiFilin** [comment]
Change code to this

https://gist.github.com/Hugo16bm/6c5f0cbb7987f882c4389f7da09fb48d

**Comment by Niziol** [comment]
> Change code to this
> 
> [gist.github.com/Hugo16bm/6c5f0cbb7987f882c4389f7da09fb48d](https://gist.github.com/Hugo16bm/6c5f0cbb7987f882c4389f7da09fb48d)_ (too large to embed)_

That's the code for **PermissionsViewer** (Allows you to view a user's permissions.), and above was the bug for **RoleMembers** (Allows you to see the members of each role on a server.).

So link above is incorrect
