### ISSUE TITLE
no color in roles, no color in voice[Bug] 

### ISSUE THREAD

**Issue by CerBerSith** [zerebos/BetterDiscordAddons#773]
**Which plugin/theme is this about?**

BetterRoleColors
v0.10.2от Zerebos
**Describe the Bug**

no color in roles, no color in voice
**To Reproduce**

**Expected Behavior**

**Screenshots**

![image](https://github.com/user-attachments/assets/bb985344-4f50-407a-8ccf-e702508a775b)

**Discord Version**

stable 308381 (a65c916) Host 1.0.9153 x64 (49397) Build Override: N/A Windows 11 64-bit (10.0.22631)
**Additional Context**

**Comment by vicimpa** [comment]
[BetterRoleColors.plugin.js.zip](https://github.com/user-attachments/files/16321708/BetterRoleColors.plugin.js.zip)
![telegram-cloud-photo-size-2-5249400456596284034-x](https://github.com/user-attachments/assets/0751edcf-16d0-4810-b02d-62e7d75404c1)
Maybe my fix help you?)

**Comment by bigyihsuan** [comment]
> [BetterRoleColors.plugin.js.zip](https://github.com/user-attachments/files/16321708/BetterRoleColors.plugin.js.zip) ![telegram-cloud-photo-size-2-5249400456596284034-x](https://private-user-images.githubusercontent.com/25244507/350706698-0751edcf-16d0-4810-b02d-62e7d75404c1.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0MzgwMjUsIm5iZiI6MTcyNjQzNzcyNSwicGF0aCI6Ii8yNTI0NDUwNy8zNTA3MDY2OTgtMDc1MWVkY2YtMTZkMC00ODEwLWIwMmQtNjJlN2Q3NTQwNGMxLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE1VDIyMDIwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk1Njk0OTQ1YWFjOTc0MGZjOTc4YjFiODYwNjU5MzNkYjE2Mjg1OGI4NzIyMTdjN2Y4MWUyYmYyMThiYTk4MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BpI7skE8y3jQ5pTyhQWVPHFqME5IAxttQgK07XclR1k) Maybe my fix help you?)

This works, but what exactly did you change? You should make a pull request so that the fix gets merged in.
