### ISSUE TITLE
[Bug] Permissions in the user pop-up got a little broken.

### ISSUE THREAD

**Issue by Czerwony150** [zerebos/BetterDiscordAddons#776]
**Which plugin/theme is this about?**
PermissionsViewer
v0.2.10

**Describe the Bug**
Broken appearance of permissions in pop-up user menu

**Expected Behavior**
It should land just like the current roles design

**Screenshots**
![image](https://github.com/user-attachments/assets/4fadb7cf-406c-4a36-b86a-3cfa8d8f8ee3)

**Discord Version**
stable 327180 (bd5e7f6) Host 1.0.9163 x64 (52153) Build Override: N/A Windows 11 64-bit (10.0.22631)

**Comment by zerebos** [comment]
This is weird, I'm on the same version but it looks fine for me

**Comment by Czerwony150** [comment]
> This is weird, I'm on the same version but it looks fine for me

Okay, deleting the cache folders fixed the problem. It's possible that it's due to an earlier custom patch fixing the plugin
![image](https://github.com/user-attachments/assets/cde36300-1de6-4158-b631-1bd4686921dc)

**Comment by zerebos** [comment]
Make sure you're using only the official version of the plugin with no patches, no custom css and no themes to test

**Comment by zerebos** [comment]
Looks like there was indeed a chance by Discord, such bad timing. Fixed with the latest version though
