### ISSUE TITLE
[Feature] Role Colors outlining screenshare?

### ISSUE THREAD

**Issue by pomarf** [zerebos/BetterDiscordAddons#777]
**Which plugin/theme is this about?**
BetterRoleColors

**Is your feature request related to a problem? Please describe.**
It's hard to know quickly who's screen is whose when you are watching multiple people at the same time while playing games to get their perspectives in real time.

**Describe the feature you'd like**
It would be really cool if you could add an outline to the outside of each screenshare as to help alleviate that problem a bit.

**Additional context**
I know that there is already an outline on screenshares for people who have nitro (I think that's what causes it, I'm not 100% sure) but maybe it's possible to hijack that element?

**Comment by zerebos** [comment]
Sorry but BetterRoleColors has been discontinued. I recommend using [MoreRoleColors](https://betterdiscord.app/plugin/MoreRoleColors). I will CC the creator @daddyboard about your feature request!
