### ISSUE TITLE
[Bug]  HideDisabledEmojis not work

### ISSUE THREAD

**Issue by hokagegaara** [zerebos/BetterDiscordAddons#778]
HideDisabledEmojis not work
![изображение](https://github.com/user-attachments/assets/c50da75c-e551-4b0b-a115-7e822ed1148f)
![изображение](https://github.com/user-attachments/assets/343cbfd4-a4ce-4b95-944c-b991c8c3aa06)

**Comment by b1k3rdude** [comment]
I think what the OP means and I believe I have the same issue, is that in the beginning 'HideDisabledEmojis' would hide the whole pink/purple section. I would nice to be able to hide that entire section if that's at all possible..?

**Comment by AAUCrisp** [comment]
I have the same issue.
Was hoping I could fix it by using some _Custom CSS_ but the _Discord_ crew have made it extra annoying...
I might be able to figure it out, but I've given op for now.

I'm getting **really** tired of their push for _Nitro_ money.
