### ISSUE TITLE
[Bug] BetterRoleColors periodically asking for updates even though it's already updated

### ISSUE THREAD

**Issue by Fungustober** [zerebos/BetterDiscordAddons#779]
**Which plugin/theme is this about?**
This bug report is about BetterRoleColors.

**Describe the Bug**
Every few hours, I get the "a plugin has an update!" popup at the top of my screen. After clicking update, it says "plugin updated from 0.10.2 to 0.10.3" every time.

**To Reproduce**
I genuinely have no idea it just happens every so often.

**Expected Behavior**
The plugin not asking to be updated to a version that it's already at every few hours.

**Screenshots**
<img width="905" alt="updatings" src="https://github.com/user-attachments/assets/21bff088-40ef-4022-94e4-bb49bb6368bd">
(it just happened again, ~1 hour after I opened this issue)

**Discord Version**
stable 327180 (bd5e7f6) Host 1.0.9163 x64 (52153) Build Override: N/A Windows 10 64-bit (10.0.19045)

**Comment by zerebos** [comment]
Manually update your plugin and ensure you have no other versions installed

**Comment by Fungustober** [comment]
It seems to have fixed itself now. I had an issue with a driver that crashed my computer a little while after I posted this, and after restarting I didn't see the issue anymore, so it's possible they were connected somehow.
