### ISSUE TITLE
[Bug] PermissionsViewer - Zerebos - When I click "Permissions" it doesn't show up anything

### ISSUE THREAD

**Issue by Honzjas25** [zerebos/BetterDiscordAddons#783]
**Which plugin/theme is this about?**

 _PermissionsViewer_

**Describe the Bug**

When I click "Permissions" on Server/user/Channel it doesn't anything and also on profile doesn't show perms too of roles.
 
**To Reproduce**

-
**Expected Behavior**

-
**Screenshots**

![image](https://github.com/user-attachments/assets/06bf213b-0876-4cbc-a8c3-44762d55846f)

**Discord Version**

Stable 329244 (b4f6cfc)
 
**Additional Context**

When channel doesn't have any roles to be restricted it show this: so ig it works just  popouts doesn't work and so go on.
![image](https://github.com/user-attachments/assets/05fa54dc-8d23-43dd-bfa4-b646a0fa9b4c)

**Comment by zerebos** [comment]
Is the first screenshot yourself? Can you try without a theme that may be hiding it?

The second one is not an issue, that means there are no channel-specific overrides.

**Comment by Honzjas25** [comment]
Howdy Zerebos! No, that wasn't my acc here is my acc. with screenshot: 
![image](https://github.com/user-attachments/assets/53cf9892-b4fc-4b37-998e-1bd2eb4d702b)

 Yes even without theme it doesn't show anything when I click **"Permissions"** on server/channel also when I click on user it doesn't option for **"Permissions"** like it used to do: 
![image](https://github.com/user-attachments/assets/0144ce19-2a66-4500-a5af-7b6711225e8a)

Well yes even my profile and on other users it doesn't show any permissions. - 
![image](https://github.com/user-attachments/assets/86d5cfd8-02d8-4de2-86e4-682a4ab06d0b)

@zerebos

**Comment by Vanello1908** [comment]
@zerebos 
I've discovered where is problem
![image](https://github.com/user-attachments/assets/98e3dfb3-e1c1-40be-b668-56b8e08027e2)
![image](https://github.com/user-attachments/assets/a07cb5a8-6d32-4d9b-837a-922e9c4b433d)
![image](https://github.com/user-attachments/assets/c77b7bef-55b4-4354-a93e-0aecbc6fea02)
There isn't a function called GuildStore.getRoles

**Comment by zerebos** [comment]
This will be fixed as part of the rewrite I am doing for #800
