### ISSUE TITLE
[Bug] PermissionsViewer 

### ISSUE THREAD

**Issue by GK0starik** [zerebos/BetterDiscordAddons#784]
**Which plugin/theme is this about?**
PermissionsViewer 

**Describe the Bug**
the button does not respond to clicks

**To Reproduce**
Right-click, select permissions

**Expected Behavior**
Opening a menu with permissions

**Screenshots**
https://imgur.com/a/RHojsNY

**Discord Version**
Stable

**Additional Context**

**Comment by LeoneVi** [comment]
I'm having the same issue

**Comment by Kleb64** [comment]
Getting this error in the console when I try.
![Screenshot 2024-09-22 222227](https://github.com/user-attachments/assets/cb728a11-e6cf-4d90-9437-1e068d46afac)

**Comment by zerebos** [comment]
Duplicate of #783
