### ISSUE TITLE
[Bug] RoleMembers not showing on context menu

### ISSUE THREAD

**Issue by AhmedSherif0904** [zerebos/BetterDiscordAddons#786]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
RoleMembers plugin not showing in context menu not sure if it is me or global issue

**To Reproduce**
Dunno

**Expected Behavior**
It should show in context menu

**Screenshots**
![image](https://github.com/user-attachments/assets/0c8d3048-f53a-4dbf-ac3f-0a9e2090f81c)

**Discord Version**
Stable

**Additional Context**
Nothing

**Comment by zerebos** [comment]
This should be fixed with the latest version!
