### ISSUE TITLE
[Bug] RoleMembers not showing in context menu

### ISSUE THREAD

**Issue by idk2124234** [zerebos/BetterDiscordAddons#787]
**Which plugin/theme is this about?**
RoleMembers

**Describe the Bug**
Plugin not showing in context menu

**To Reproduce**
Literally just enable the plugin

**Expected Behavior**
Role Members should show in context menu
![{9535BD8D-E85D-4B9B-B2BC-95F0BFB55DC4}](https://github.com/user-attachments/assets/0e784f1d-9400-4e53-bb18-23b7472f7b1e)

**Comment by idk2124234** [comment]
@zerebos pls fix

**Comment by fuzeduze** [comment]
I have the same issue, and the mention option have the same problem! Thank you in advance!
![image](https://github.com/user-attachments/assets/618699f4-4cb6-438c-a5f0-cb4a02c1af07)

**Comment by idk2124234** [comment]
@iDeparture what version of rolemembers r u on?

**Comment by idk2124234** [comment]
@iDeparture thats not the same thing that roles is working but when clicking on a server ur supposed to see all roles and click on a role to see who has that role

**Comment by idk2124234** [comment]
> > **Which plugin/theme is this about?** RoleMembers
> > **Describe the Bug** Plugin not showing in context menu
> > **To Reproduce** Literally just enable the plugin
> > **Expected Behavior** Role Members should show in context menu ![{9535BD8D-E85D-4B9B-B2BC-95F0BFB55DC4}](https://private-user-images.githubusercontent.com/139180452/372246530-0e784f1d-9400-4e53-bb18-23b7472f7b1e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc3OTk2MjIsIm5iZiI6MTcyNzc5OTMyMiwicGF0aCI6Ii8xMzkxODA0NTIvMzcyMjQ2NTMwLTBlNzg0ZjFkLTk0MDAtNGU1My1iYjE4LTIzYjc0NzJmN2IxZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAwMVQxNjE1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00MmMyYmE2Y2Y5ZjhkYTc5YzJhZTE3YzMyY2NjYjVmOTY5NzIxZGE5YTViODFiYzRlNmNlNmQzN2NiMjA1ZDkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.Rnidc3-QFsOSr4_t7x5fsD3rXdaoCd2BqDEJRLDFJl0)
> 
> its working for me scratch that, is PermissionsViewer and Channel Permissions not working for anyone?
> 
> ![image](https://private-user-images.githubusercontent.com/92184134/372559640-3c187b59-91aa-41a7-b5b2-8ebcd783d4c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTgyMzAsIm5iZiI6MTcyODIxNzkzMCwicGF0aCI6Ii85MjE4NDEzNC8zNzI1NTk2NDAtM2MxODdiNTktOTFhYS00MWE3LWI1YjItOGViY2Q3ODNkNGM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEyMzIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhOTNmMGFmNDdmNjY3YTk1NDdlN2RjMjhkNjQzMDA0YWEyN2JkZWJhNGQxYjNlYmYzMGYwMDlkMzE0YmY3ODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.pQYuLe5mhVrhN3Q3Erc3zGkOSuucAJRy7cgHdI8VMRk)
> 
> ![image](https://private-user-images.githubusercontent.com/92184134/372559782-98e3f0d7-226d-468b-a4ab-910aa812d91f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgyMTgyMzAsIm5iZiI6MTcyODIxNzkzMCwicGF0aCI6Ii85MjE4NDEzNC8zNzI1NTk3ODItOThlM2YwZDctMjI2ZC00NjhiLWE0YWItOTEwYWE4MTJkOTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA2VDEyMzIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQxMTI2ZTAxZjc3ODkzOWFkMzQwYTdiZjRhNDg5ZDQ4NTlhMzg2NmNmNTY1YjFhZmZiNjI5ZDMzZjE5ZmM2NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.toD1_o1Casmh6K2ccxPaBz0LpWx-9ZYYpJej25xv4wE)

thats not the same thing that roles is working but when clicking on a server ur supposed to see all roles and click on a role to see who has that role

**Comment by Teteros** [comment]
PR #792 addresses this but if you don't wanna rebuild the plugin you can do this

Go to Plugins -> RoleMembers and Edit code :gear: 
and edit and save the `GuildStore` line to fix it: 
```diff
--- a/src/plugins/RoleMembers/index.js
+++ b/src/plugins/RoleMembers/index.js
@@ -10,7 +10,7 @@ module.exports = (Plugin, Api) => {
     const filter = (obj, predicate) => from(Object.entries(obj).filter((o) => {return predicate(o[1]);}));
 
     const SelectedGuildStore = DiscordModules.SelectedGuildStore;
-    const GuildStore = DiscordModules.GuildStore;
+    const GuildStore = Webpack.getStore("GuildStore");
     const GuildMemberStore = DiscordModules.GuildMemberStore;
     const UserStore = DiscordModules.UserStore;
     const ImageResolver = DiscordModules.ImageResolver;
```

**Comment by idk2124234** [comment]
> PR #792 addresses this but if you don't wanna rebuild the plugin you can do this
> 
> Go to Plugins -> RoleMembers and Edit code ⚙️ and edit and save the `GuildStore` line to fix it:
> 
> ```diff
> --- a/src/plugins/RoleMembers/index.js
> +++ b/src/plugins/RoleMembers/index.js
> @@ -10,7 +10,7 @@ module.exports = (Plugin, Api) => {
>      const filter = (obj, predicate) => from(Object.entries(obj).filter((o) => {return predicate(o[1]);}));
>  
>      const SelectedGuildStore = DiscordModules.SelectedGuildStore;
> -    const GuildStore = DiscordModules.GuildStore;
> +    const GuildStore = Webpack.getStore("GuildStore");
>      const GuildMemberStore = DiscordModules.GuildMemberStore;
>      const UserStore = DiscordModules.UserStore;
>      const ImageResolver = DiscordModules.ImageResolver;
> ```

Thx. It Worked

**Comment by Danny-Boii** [comment]
> PR #792 addresses this but if you don't wanna rebuild the plugin you can do this
> 
> Go to Plugins -> RoleMembers and Edit code ⚙️ and edit and save the `GuildStore` line to fix it:
> 
> ```diff
> --- a/src/plugins/RoleMembers/index.js
> +++ b/src/plugins/RoleMembers/index.js
> @@ -10,7 +10,7 @@ module.exports = (Plugin, Api) => {
>      const filter = (obj, predicate) => from(Object.entries(obj).filter((o) => {return predicate(o[1]);}));
>  
>      const SelectedGuildStore = DiscordModules.SelectedGuildStore;
> -    const GuildStore = DiscordModules.GuildStore;
> +    const GuildStore = Webpack.getStore("GuildStore");
>      const GuildMemberStore = DiscordModules.GuildMemberStore;
>      const UserStore = DiscordModules.UserStore;
>      const ImageResolver = DiscordModules.ImageResolver;
> ```

"a/src/plugins/RoleMembers/index.js" nor "@@ -10,7 +10,7 @@ module.exports = (Plugin, Api) => {" are appearing for me in the code, where would I place the change at?

**Comment by Danny-Boii** [comment]
> PR #792 addresses this but if you don't wanna rebuild the plugin you can do this
> 
> Go to Plugins -> RoleMembers and Edit code ⚙️ and edit and save the `GuildStore` line to fix it:
> 
> ```diff
> --- a/src/plugins/RoleMembers/index.js
> +++ b/src/plugins/RoleMembers/index.js
> @@ -10,7 +10,7 @@ module.exports = (Plugin, Api) => {
>      const filter = (obj, predicate) => from(Object.entries(obj).filter((o) => {return predicate(o[1]);}));
>  
>      const SelectedGuildStore = DiscordModules.SelectedGuildStore;
> -    const GuildStore = DiscordModules.GuildStore;
> +    const GuildStore = Webpack.getStore("GuildStore");
>      const GuildMemberStore = DiscordModules.GuildMemberStore;
>      const UserStore = DiscordModules.UserStore;
>      const ImageResolver = DiscordModules.ImageResolver;
> ```

thanks as well. Do you know approximately how large the server has to be before the script stops working? Some bigger servers get 0 returns in the member list while smaller ones work as intended. Thanks again

**Comment by DaddyBoard** [comment]
> > PR #792 addresses this but if you don't wanna rebuild the plugin you can do this
> > Go to Plugins -> RoleMembers and Edit code ⚙️ and edit and save the `GuildStore` line to fix it:
> > ```diff
> > --- a/src/plugins/RoleMembers/index.js
> > +++ b/src/plugins/RoleMembers/index.js
> > @@ -10,7 +10,7 @@ module.exports = (Plugin, Api) => {
> >      const filter = (obj, predicate) => from(Object.entries(obj).filter((o) => {return predicate(o[1]);}));
> >  
> >      const SelectedGuildStore = DiscordModules.SelectedGuildStore;
> > -    const GuildStore = DiscordModules.GuildStore;
> > +    const GuildStore = Webpack.getStore("GuildStore");
> >      const GuildMemberStore = DiscordModules.GuildMemberStore;
> >      const UserStore = DiscordModules.UserStore;
> >      const ImageResolver = DiscordModules.ImageResolver;
> > ```
> 
> thanks as well. Do you know approximately how large the server has to be before the script stops working? Some bigger servers get 0 returns in the member list while smaller ones work as intended. Thanks again

Could you share a Console log if there's any errors when it fails to pull users in larger servers? 

I pushed the fix via a PR for this and wouldn't mind fixing this issue if you can provide more information

**Comment by Danny-Boii** [comment]
Unfortunately, I don't really get any errors in console, just a really botched pull. A server with thousands of members only conjures up 19 people in a selected role (obviously a disparity). Meanwhile, my small circle servers get accurate returns
![image](https://github.com/user-attachments/assets/62dd0829-ab3d-4707-9f8b-b2a84598580d)
