### ISSUE TITLE
[Bug] BetterRoleColors crashing Discord in any channel where someone is typing.

### ISSUE THREAD

**Issue by New-bliss** [zerebos/BetterDiscordAddons#789]
**Which plugin/theme is this about?**
BetterRoleColors

**Describe the Bug**
Whenever someone begins typing in a channel, this plugin instantly crashes Discord.

**To Reproduce**
If "X is typing..." is visible, Discord crashes.

**Expected Behavior**
Color Typing Indicators without crashing.

**Screenshots**
It's just the basic crash screen and the "Press to restart" or "respawn", as the screen says.

**Discord Version**
PTB, latest.

**Additional Context**
Started around a month back, assuming it was related to an update breaking something I disabled it in the meantime. I decided to try again today, and it still crashes the client.

If you need logs or anything, let me know.

**Comment by zerebos** [comment]
Sorry but BetterRoleColors has been discontinued. I recommend using [MoreRoleColors](https://betterdiscord.app/plugin/MoreRoleColors).
