### ISSUE TITLE
[Bug] color roles not working

### ISSUE THREAD

**Issue by srink007** [zerebos/BetterDiscordAddons#799]
**Which plugin/theme is this about?**
betterrolecolors

**Describe the Bug**
Not working.

![Uploading Screenshot 2024-12-12 at 15.19.02.png…]()

**Discord Version**
Stable

**Additional Context**
It used to work

**Comment by zerebos** [comment]
Sorry but BetterRoleColors has been discontinued. I recommend using [MoreRoleColors](https://betterdiscord.app/plugin/MoreRoleColors).
